apiVersion: v1
kind: Service
metadata:
  name: webfinanceiro
  namespace: webfinanceiro
spec:
  type: NodePort
  selector:
    app: webfinanceiro
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
